service: aws-appsync-chat
frameworkVersion: '3'

custom:
  ddbTableName:
    chatTable: 'chatTable'
    userTable: 'userTable'
    sessionTokenTable: 'sessionTokenTable'
  appSync:
    - name: 'chatRoom'
      schema: schema.api.graphql
      authenticationType: AWS_LAMBDA
      lambdaAuthorizerConfig:
        functionName: lambdaAuthorizer
      additionalAuthenticationProviders:
        - authenticationType: API_KEY
      mappingTemplatesLocation: mapping-templates
      mappingTemplates:
        - dataSource: ChatRoom
          type: Mutation
          field: sendChat
          kind: PIPELINE
          functions:
            - getReceiverRoom
            - sendChat
          request: "Mutation.sendChat.request.vtl"
          response: "Mutation.sendChat.response.vtl"
        - dataSource: ChatRoom
          type: Query
          field: getChatRoom
          request: "Query.getChatRoom.request.vtl"
          response: "Query.getChatRoom.response.vtl"
        - dataSource: ChatRoom
          type: Query
          field: getDMList
          request: "Query.getDMList.request.vtl"
          response: "Query.getDMList.response.vtl"
        - dataSource: ChatRoom
          type: Subscription
          field: newChat
          request: "Subscription.newChat.request.vtl"
          response: "Subscription.newChat.response.vtl"
        - dataSource: register
          type: Mutation
          field: register
          request: "Mutation.register.request.vtl"
          response: "Mutation.register.response.vtl"
        - dataSource: login
          type: Mutation
          field: login
          request: "Mutation.login.request.vtl"
          response: "Mutation.login.response.vtl"
      functionConfigurations:
        - name: getReceiverRoom
          dataSource: ChatRoom
          request: "getReceiverRoom.request.vtl"
          response: "getReceiverRoom.response.vtl"
        - name: sendChat
          dataSource: ChatRoom
          request: "sendChat.request.vtl"
          response: "sendChat.response.vtl"
      dataSources:
        - type: AMAZON_DYNAMODB
          name: ChatRoom
          config:
            tableName: ${self:custom.ddbTableName.chatTable}
        - type: AWS_LAMBDA
          name: register
          config:
            functionName: register
        - type: AWS_LAMBDA
          name: login
          config:
            functionName: login

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  environment:
    CHAT_TABLE_NAME: ${self:custom.ddbTableName.chatTable}
    USER_TABLE_NAME: ${self:custom.ddbTableName.userTable}
    SESSION_TOKEN_TABLE_NAME: ${self:custom.ddbTableName.sessionTokenTable}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - lambda:InvokeFunction
          Resource:
            - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.ddbTableName.chatTable}'
            - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.ddbTableName.chatTable}/*'
            - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.ddbTableName.userTable}'
            - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.ddbTableName.sessionTokenTable}'

resources:
  Resources:
    chatTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ddbTableName.chatTable}
        AttributeDefinitions:
          - AttributeName: roomType
            AttributeType: S
          - AttributeName: roomId
            AttributeType: S
          - AttributeName: chatId
            AttributeType: S
        KeySchema:
          - AttributeName: roomType
            KeyType: HASH
          - AttributeName: roomId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: dmIndex
            KeySchema:
              - AttributeName: roomType
                KeyType: HASH
              - AttributeName: chatId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ddbTableName.userTable}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    sessionTokenTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ddbTableName.sessionTokenTable}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
          - AttributeName: sessionToken
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
          - AttributeName: sessionToken
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  lambdaAuthorizer:
    handler: functions/lambdaAuthorizer.handler
  register:
    handler: functions/register.handler
  login:
    handler: functions/login.handler